spring:
  application:
    name: cursoIntroductorio

server:
  error:
    include-message: always

logging:
  level:
    practica.curso.curso: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  misurl:
    database: "https://midatabase.com"

